footprint: [[-0.6, -0.3], [-0.6, 0.3], [0.2, 0.3], [0.2, -0.3]]
footprint_padding: 0.01

#For this example we'll configure the costmap in voxel-grid mode
obstacle_layer:
  map_type: voxel

  #Voxel grid specific parameters
  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 10
  unknown_threshold: 9


  #Set the tolerance we're willing to have for tf transforms
  transform_tolerance: 0.3

  #Obstacle marking parameters
  obstacle_range: 2.5
  max_obstacle_height: 2.0
  raytrace_range: 3.0

  #Cost function parameters
  inflation_radius: 0.7
  cost_scaling_factor: 10.0

  #The cost at which a cell is considered an obstacle when a map is read from the map_server
  lethal_cost_threshold: 100

  #Configuration for the sensors that the costmap will use to update a map
  observation_sources: laser_scan_sensor point_cloud_sensor

  laser_scan_sensor: {sensor_frame: base_laser, data_type: LaserScan, topic: /scan_filtered, expected_update_rate: 0.5,
     marking: true, clearing: true, max_obstacle_height: 1, min_obstacle_height: 0.08}

  point_cloud_sensor: {sensor_frame: sensor_frame, data_type: PointCloud, topic: /cloud, marking: true, clearing: true}

sonar_layer:
  topics: [ '/ultrasonic_fr', '/ultrasonic_fm', '/ultrasonic_fl', '/ultrasonic_br', '/ultrasonic_bm', '/ultrasonic_bl', '/ultrasonic_rm', '/ultrasonic_lm', '/ultrasonic_r', '/ultrasonic_l' ]
  no_readings_timeout: 1.0
  clear_on_max_reading: true


