obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.36, -0.275], [-0.36, 0.275], [0.36, 0.275], [0.36, -0.275]]
footprint_padding: 0.01
#robot_radius: 0.5
#inflation_radius: 0.55

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: base_laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: sensor_frame, data_type: PointCloud, topic: /cloud, marking: true, clearing: true}