local_costmap:
  global_frame: odom_gazebo
  robot_base_frame: chassis_link
  update_frequency: 10.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.08
  origin_x: 0.0
  origin_y: 0.0
  
  
  inflation_layer:
    inflation_radius: 3
    cost_scaling_factor: 10.0
