local_costmap:
  global_frame: odom_gazebo
  robot_base_frame: base_link_gazebo
  update_frequency: 30.0
  publish_frequency: 20.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  
  
  inflation_layer:
    inflation_radius: 3
    cost_scaling_factor: 0.5
