obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.3, -0.3], [-0.3, 0.3], [0.6, 0.3], [0.6, -0.3]]
footprint_padding: 0.01
#robot_radius: 0.5
#inflation_radius: 0.55

#cost_scaling_factor: 0.1

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: pointcloud, data_type: PointCloud, topic: /zed/pointcloud, marking: true, clearing: true}
