#Independent settings for the local planner's costmap. Detailed descriptions of these parameters can be found at http://www.ros.org/wiki/costmap_2d

local_costmap:
  #We'll publish the voxel grid used by this costmap
  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    # - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}

  publish_voxel_map: true

  #Set the global and robot frames for the costmap
  global_frame: odom
  robot_base_frame: base_link

  #Set the update and publish frequency of the costmap
  update_frequency: 5.0
  publish_frequency: 4.0

  #We'll configure this costmap to be a rolling window... meaning it is always
  #centered at the robot
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.15
  origin_x: -0.25
  origin_y: 0.0

  inflation_layer:
    inflation_radius: 3
    cost_scaling_factor: 10.0
