odom_frame: odom
base_frame: chassis_link
map_frame: map
map_update_interval: 5.0 # Publish new map
maxUrange: 19.0 # Should be just less than sensor range
maxRange: 20.0 # Should be just greater than sensor range
particles: 1 # Increased from 80

# Update frequencies
linearUpdate: 1.0
angularUpdate: 0.5
temporalUpdate: -1.0
resampleThreshold: 0.1  # 0.3

# Initial Map Size
xmin: -100.0
ymin: -100.0
xmax: 100.0
ymax: 100.0
delta: 0.1 #Resolution

# All default
sigma: 0.08 # 0.05
kernelSize: 0.5 # 0.5
lstep: 1.2
astep: 1.2
iterations: 5
lsigma: 0.075 #0.075
ogain: 3.0 # 3.0
lskip: 0 # 0
llsamplerange: 0.2 #0.2
llsamplestep: 0.3 #0.3
lasamplerange: 0.3 #0.3
lasamplestep: 0.3 # 0.3