#Independent settings for the global planner's costmap. Detailed descriptions of these parameters can be found at http://www.ros.org/wiki/costmap_2d

global_costmap:
  #Set the global and robot frames for the costmap
  # plugins:
    # - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}
  
  global_frame: /map
  robot_base_frame: base_link

  #Set the update and publish frequency of the costmap
  update_frequency: 1.0
  publish_frequency: 0.5

  #We'll use a map served by the map_server to initialize this costmap
  static_map: true
  rolling_window: false
  resolution: 0.1

  inflation_layer:
    inflation_radius: 0.8
    cost_scaling_factor: 5.0
